/*

 BACKTEXTTRYAGAIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : BackTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackTextTryAgainWidth 20
#define BackTextTryAgainHeight 2
#define BackTextTryAgainBank 0

extern unsigned char BackTextTryAgain[];

/* End of BACKTEXTTRYAGAIN.H */
