/*

 BACKTEXTHATCH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2019_11_Tamagotchi\Background\BackTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackTextHatchWidth 20
#define BackTextHatchHeight 2
#define BackTextHatchBank 0

extern unsigned char BackTextHatch[];

/* End of BACKTEXTHATCH.H */
