/*

 BACKTOPICONS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : Q:\PROJECTS\PERSONAL\GAMES\2019_11_Tamagotchi\Background\BackTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackTopIconsWidth 20
#define BackTopIconsHeight 2
#define BackTopIconsBank 0

extern unsigned char BackTopIcons[];

/* End of BACKTOPICONS.H */
