/*

 CURSORSPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char CursorSprites[] =
{
  0xF8,0xF8,0xF8,0x88,0xF8,0xB8,0xE0,0xA0,
  0xE0,0xE0,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x7C,0x7C,0x7C,0x44,0x7C,0x5C,
  0x70,0x50,0x70,0x70,0x00,0x00,0x00,0x00
};

/* End of CURSORSPRITES.C */
